// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBackend struct {
	_          structs.HostLayout
	Nsip       bpfIpAddr
	NodeIp     bpfIpAddr
	NodePort   uint16
	OnThisNode uint8
	Pad        uint8
}

type bpfCfgVal struct {
	_                structs.HostLayout
	NicIfindex       uint32
	NodeIp           bpfIpAddr
	TunnelPort       uint16
	HaveRedirectPeer uint8
	Pad              uint8
}

type bpfFlowCtRevVal struct {
	_           structs.HostLayout
	OrigSrcNsip bpfIpAddr
	OrigDstVip  bpfIpAddr
}

type bpfFlowCtVal struct {
	_             structs.HostLayout
	BackendNsip   bpfIpAddr
	NodeIp        bpfIpAddr
	NodePort      uint16
	Pad           [2]uint8
	SrcInstanceIp bpfIpAddr
}

type bpfFlowKey struct {
	_     structs.HostLayout
	Saddr bpfIpAddr
	Daddr bpfIpAddr
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type bpfIpAddr struct {
	_    structs.HostLayout
	Addr [16]uint8
}

type bpfLocalInstanceVal struct {
	_           structs.HostLayout
	VethIfindex uint32
	PeerIfindex uint32
}

type bpfServiceBackendsVal struct {
	_        structs.HostLayout
	Policy   uint8
	Pad      [3]uint8
	Count    uint32
	Backends [16]bpfBackend
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TcDecap  *ebpf.ProgramSpec `ebpf:"tc_decap"`
	TcEgress *ebpf.ProgramSpec `ebpf:"tc_egress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Cfg             *ebpf.MapSpec `ebpf:"cfg"`
	FlowCt          *ebpf.MapSpec `ebpf:"flow_ct"`
	FlowCtRev       *ebpf.MapSpec `ebpf:"flow_ct_rev"`
	InstanceIp      *ebpf.MapSpec `ebpf:"instance_ip"`
	LocalInstances  *ebpf.MapSpec `ebpf:"local_instances"`
	ServiceBackends *ebpf.MapSpec `ebpf:"service_backends"`
	Slowpath        *ebpf.MapSpec `ebpf:"slowpath"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Cfg             *ebpf.Map `ebpf:"cfg"`
	FlowCt          *ebpf.Map `ebpf:"flow_ct"`
	FlowCtRev       *ebpf.Map `ebpf:"flow_ct_rev"`
	InstanceIp      *ebpf.Map `ebpf:"instance_ip"`
	LocalInstances  *ebpf.Map `ebpf:"local_instances"`
	ServiceBackends *ebpf.Map `ebpf:"service_backends"`
	Slowpath        *ebpf.Map `ebpf:"slowpath"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Cfg,
		m.FlowCt,
		m.FlowCtRev,
		m.InstanceIp,
		m.LocalInstances,
		m.ServiceBackends,
		m.Slowpath,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TcDecap  *ebpf.Program `ebpf:"tc_decap"`
	TcEgress *ebpf.Program `ebpf:"tc_egress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TcDecap,
		p.TcEgress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
