name: Node Net Manager Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: node-net-manager/go.mod

      - name: Install dependencies
        working-directory: node-net-manager
        run: |
          go mod download

      - name: Vet
        working-directory: node-net-manager
        run: |
          go vet ./...

      - name: Run test suite
        working-directory: node-net-manager
        run: |
           go test ./...
